-- V1: Initial Schema for EduChain

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(200) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'STUDENT',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    accreditation_number VARCHAR(100) UNIQUE,
    contact_email VARCHAR(200),
    contact_phone VARCHAR(50),
    website VARCHAR(255),
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    logo_url VARCHAR(500),
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_id VARCHAR(100) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    phone VARCHAR(50),
    country VARCHAR(100),
    date_of_birth DATE,
    photo_url VARCHAR(500),
    did VARCHAR(255) UNIQUE,
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    institution_id BIGINT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    field_of_study VARCHAR(255),
    credential_type VARCHAR(50) NOT NULL DEFAULT 'DEGREE',
    issue_date DATE NOT NULL,
    expiry_date DATE,
    grade VARCHAR(50),
    honors VARCHAR(100),
    qr_code_url VARCHAR(500),
    hash VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    revocation_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100),
    entity_id BIGINT,
    action VARCHAR(100) NOT NULL,
    actor_email VARCHAR(200),
    details TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_credentials_student ON credentials(student_id);
CREATE INDEX IF NOT EXISTS idx_credentials_hash ON credentials(hash);
CREATE INDEX IF NOT EXISTS idx_students_email ON students(email);
CREATE INDEX IF NOT EXISTS idx_students_did ON students(did);

-- Demo seed data
INSERT INTO users (username, email, password, role) VALUES
    ('admin', 'admin@educhain.africa', '$2a$10$FfN4p5h0MqLpnBYeoii0Jehbwa0fYne61/tGld4SxwcplNDsZnENW', 'PLATFORM_ADMIN'),
    ('univ_yaounde', 'contact@uy1.cm', '$2a$10$FfN4p5h0MqLpnBYeoii0Jehbwa0fYne61/tGld4SxwcplNDsZnENW', 'INSTITUTION_ADMIN'),
    ('john_doe', 'john.doe@student.educhain.africa', '$2a$10$FfN4p5h0MqLpnBYeoii0Jehbwa0fYne61/tGld4SxwcplNDsZnENW', 'STUDENT'),
    ('jane_smith', 'jane.smith@student.educhain.africa', '$2a$10$FfN4p5h0MqLpnBYeoii0Jehbwa0fYne61/tGld4SxwcplNDsZnENW', 'STUDENT')
;

INSERT INTO institutions (name, country, accreditation_number, contact_email, verified, user_id) VALUES
    ('University of Yaoundé I', 'Cameroon', 'CMR-MINSUP-001', 'contact@uy1.cm', TRUE,
     (SELECT id FROM users WHERE username = 'univ_yaounde'))
;

INSERT INTO students (first_name, last_name, email, country, did, user_id) VALUES
    ('John', 'Doe', 'john.doe@student.educhain.africa', 'Cameroon',
     'did:educhain:cmr:johndoe001', (SELECT id FROM users WHERE username = 'john_doe')),
    ('Jane', 'Smith', 'jane.smith@student.educhain.africa', 'Nigeria',
     'did:educhain:nga:janesmith002', (SELECT id FROM users WHERE username = 'jane_smith'))
;

INSERT INTO credentials (student_id, institution_id, title, field_of_study, credential_type, issue_date, grade, honors, hash, status) VALUES
    (1, 1, 'Bachelor of Science in Computer Science', 'Computer Science', 'DEGREE',
     '2024-07-15', 'A', 'Magna Cum Laude',
     'sha256:a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456', 'ACTIVE'),
    (2, 1, 'Master of Engineering in Telecommunications', 'Telecommunications', 'DEGREE',
     '2024-07-20', 'B+', 'Cum Laude',
     'sha256:b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567f', 'ACTIVE')
;
